### ISSUE TITLE
Sample screenshot is too pretty

### ISSUE THREAD

**Issue by melissaboiko** [tam-carre/polywins#7]
The demonstration gif in the README is excessively beautiful. There should be a lil pointer to the colour palette, name of the artists for the pictures, font choices, maybe theming rcfiles and the like :sparkles:

**Comment by tam-carre** [comment]
the font is azukifontB and there's a patched version somewhere in my dotfiles
artist is Noel Yoshida/noellemonade
colors are probably somewhere in the dotfiles.

**Comment by ItsTerm1n4l** [comment]
close the issue?

**Comment by tam-carre** [comment]
i apologize for the very belated reply, i don't take the time to watch and support my old repos.

**Comment by ItsTerm1n4l** [comment]
nice project btw!
